"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"""

                                            #CODE HERE:-

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        freq1 = {}
        freq2 = {}
        for i in s:
            if i not in freq1:
                freq1[i] = 1
            else:
                freq1[i] += 1
        for i in t:
            if i not in freq2:
                freq2[i] = 1
            else:
                freq2[i] += 1
        for key,value in freq2.items():
            if key in freq1.keys():
                if freq2[key] != freq1[key]:
                    return key
            else:
                return key
        